### PR TITLE
Replace deprecated string offset access syntax

### PR DESCRIPTION
**Pull request by crishoj**
This PR replaces the deprecated curly brace syntax for array and string access. 

Ref.: https://wiki.php.net/rfc/deprecate_curly_braces_array_access

### CODE REVIEW

**Comment by okaufmann** [comment]
I'm also facing this problem... Is there anything else missing to merge this @milon ?

**Comment by crishoj** [comment]
@okaufmann , alternatively, you can use the original implementation from TCPDF, which has been patched already.

```php
$barcode = new TCPDF2DBarcode($content, 'QRCODE');
$barcode->getBarcodePngData($width, $height);
```

**Comment by milon** [comment]
Thanks, @crishoj

**Comment by daaner** [comment]
The commit has not been updated. Can you release the next minor version?

**Pull request merged**
